language: python

python:
- "3.6"

branches:
  only:
    - master

install:
  - pip install coverage
  - pip install coveralls
  - pip install -U -r requirements.txt

script:
  - coverage run --source=tests,simuloc -m unittest discover tests

after_success:
  - coverage report
  - coveralls
